### ISSUE TITLE
Example Writing QuAAC files does not work 

### ISSUE THREAD

**Issue by LuisOlivaresJ** [jrkerns/quaac#2]
**Describe the bug**
validation error for Document

**To Reproduce**
Run the first example on [Writing QuAAC file section](https://quaac.readthedocs.io/en/latest/writing_quaac.html)

**Screenshots**
![Captura](https://github.com/user-attachments/assets/5ae4edf8-fbd2-4210-8af9-8eff92a95656)

**Additional context**
Changing the parameter version to '1.0', works.

**Comment by jrkerns** [comment]
Thanks! fixed in afad02eebab3b39927bca8f8bb75f0cb59dc3a28
